services:
    rasa:
      container_name: "rasa_server"
      user: root
      network_mode: host
      build: 
        context: .
        dockerfile: kubernetesDockerfile
      extra_hosts:
        - "rasax-release-rasa-x-rasa-x.rasax.svc:10.110.214.70"

    actions:
      image: rasa/rasa-sdk:3.1.2
      restart: always
      volumes: 
        - ./actions/:/app/actions
      network_mode: host